# Site settings
baseurl: /irma5
#title: Irma.jpg
email: irma.jpg@gmail.com


#background photos
index-hero: index-hero.jpg
about-hero: about-hero.jpg
blog-hero: blog-hero.jpg
contact-hero: contact-hero.jpg


# Build settings

markdown: kramdown
permalink: /:categories/:title/

include: ["_pages"]

port: 3000
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: assets/css
  style: :nested

assets:
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]
