#------------------------
# Albums section
albums:
  - name: Album1
    cover: cover1.jpg
    cover2: album1/cover1.jpg

  - name: Album2
    cover: cover2.jpg
    cover2: album2/cover2.jpg
  - name: Album3
    cover: cover3.jpg
    cover2: album3/cover3.jpg
  - name: Album4
    cover: cover4.jpg
    cover2: album4/cover4.jpg
  - name: Album5
    cover: cover5.jpg
    cover2: album5/cover5.jpg
  - name: Album6
    cover: cover6.jpg
    cover2: album6/cover6.jpg
  - name: Album7
    cover: cover7.jpg
    cover2: album7/cover7.jpg
  - name: Album8
    cover: cover8.jpg
    cover2: album8/cover8.jpg
#------------------------
# About pictures

about-pictures:
  - pic: profile.jpg
  - pic: profile2.jpg
  - pic: profile3.jpg
  - pic: profile4.jpg

#------------------------
# About skills

skills:
  - name: skill 1
    value: 7

  - name: skill 2
    value: 9

  - name: skill 3
    value: 8

  - name: skill 4
    value: 6

  - name: skill 5
    value: 10
