#------------------------
# Blogs section
blogs:
  - {title: Tihana Krpanić kao Hailey Quin, cover: blog1/blog1.jpg }
  - {title: Odbrojavanje do noći vještica, cover: blog2/blog2.jpg }
  - {title: Vikend u Rovinju sa mažoretkinjama, cover: blog3/blog3.jpg }


#------------------------
# Albums section
albums:
  - {name: Album1, cover: album1/cover1.jpg }
  - {name: Album2, cover: album2/cover2.jpg }
  - {name: Album3, cover: album3/cover3.jpg }
  - {name: Album4, cover: album4/cover4.jpg }
  - {name: Album5, cover: album5/cover5.jpg }
  - {name: Album6, cover: album6/cover6.jpg }
  - {name: Album7, cover: album7/cover7.jpg }
  - {name: Album8, cover: album8/cover8.jpg }
